# Generated by Django 3.0.4 on 2020-04-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=4000)),
                ('description', models.TextField()),
                ('box_h1', models.CharField(max_length=4000)),
                ('box_description', models.TextField()),
                ('background_image', models.ImageField(default='', upload_to='pics')),
            ],
        ),
    ]
