# Generated by Django 3.0.4 on 2020-04-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200407_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Before_Footer_Upcoming_Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hdeading', models.CharField(max_length=400)),
                ('e_description', models.TextField()),
                ('box_h2', models.CharField(max_length=400)),
                ('box_description2', models.TextField()),
                ('box_image', models.ImageField(default='', upload_to='events')),
            ],
        ),
    ]
