# Generated by Django 3.0.5 on 2020-04-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_before_footer_upcoming_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=400)),
                ('lname', models.CharField(max_length=400)),
            ],
        ),
    ]
