# Generated by Django 3.0.5 on 2020-04-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contacttest'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactlast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname1', models.CharField(max_length=40)),
                ('lastname1', models.CharField(max_length=40)),
            ],
        ),
    ]
